name: Deployment Workflow
on:
  push:
    branches:
      - master
jobs:
  jobOne:
    runs-on: ubuntu-latest
    steps:
    - name: getLatestCode    
      uses: actions/checkout@v2
    - name: deployToFTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: w01be28d.kasserver.com
        ftp-username: f013fddb
        ftp-password: ${{ secrets.FTP_PASSWORD }}
