name: Deployment Workflow
on:
  push:
    branches:
      - master
jobs:
  webDeployment:
    runs-on: ubuntu-latest
    steps:
    - name: getLatestCode
      uses: actions/checkout@v2

    - name: syncFiles
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: w01be28d.kasserver.com
        username: f013fddb
        password: xhT6FZuUmdqVyvFK
